 "use client";
import React,{createContext,useContext,useEffect,useState} from "react";
export type Product={id:string;title:string;price:number;image:string;collection:string;medium:string;dimensions:string;year:number;description:string;sold?:boolean;featured?:boolean};
export const products:Product[]=[
{id:"p1",title:"Quiet Horizon",price:1450,image:"https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=85",collection:"The Horizon",medium:"Acrylic on canvas",dimensions:"80 × 100 cm",year:2026,description:"A luminous study of distance, stillness and warm evening light.",featured:true},
{id:"p2",title:"After the Rain",price:1850,image:"https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1200&q=85",collection:"Atmospheres",medium:"Oil on canvas",dimensions:"90 × 120 cm",year:2026,description:"Soft layers and expressive marks inspired by a landscape after rain.",featured:true},
{id:"p3",title:"Golden Silence",price:2200,image:"https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1200&q=85",collection:"The Horizon",medium:"Oil on linen",dimensions:"100 × 100 cm",year:2025,description:"An atmospheric composition balancing luminous gold and deep shadow.",featured:true},
{id:"p4",title:"Blue Memory",price:1200,image:"https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&w=1200&q=85",collection:"Inner Landscapes",medium:"Mixed media",dimensions:"70 × 90 cm",year:2026,description:"A quiet abstract landscape built from translucent layers.",sold:true},
{id:"p5",title:"Wildflower Study",price:980,image:"https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=85",collection:"Botanical",medium:"Acrylic on canvas",dimensions:"60 × 80 cm",year:2025,description:"Loose botanical gestures with a contemporary palette."},
{id:"p6",title:"First Light",price:1650,image:"https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=1200&q=85",collection:"Atmospheres",medium:"Oil on canvas",dimensions:"80 × 100 cm",year:2026,description:"The first quiet minutes of daylight translated into paint."},
{id:"p7",title:"Earth & Air",price:1300,image:"https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1200&q=85",collection:"Inner Landscapes",medium:"Mixed media",dimensions:"75 × 95 cm",year:2025,description:"Organic textures and sweeping forms create a meditative balance."},
{id:"p8",title:"Ember",price:2100,image:"https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=1200&q=85",collection:"Atmospheres",medium:"Oil on linen",dimensions:"100 × 120 cm",year:2026,description:"A rich, intimate work exploring warmth and movement.",sold:true}
];
type Ctx={cart:string[];add:(id:string)=>void;remove:(id:string)=>void;clear:()=>void};
const Context=createContext<Ctx|null>(null);
export function StoreProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<string[]>([]);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("atelier-cart")||"[]"))}catch{}},[]);useEffect(()=>localStorage.setItem("atelier-cart",JSON.stringify(cart)),[cart]);const add=(id:string)=>setCart(c=>[...c,id]);const remove=(id:string)=>setCart(c=>{const i=c.indexOf(id);return i<0?c:c.filter((_,x)=>x!==i)});return <Context.Provider value={{cart,add,remove,clear:()=>setCart([])}}>{children}</Context.Provider>}
export function useStore(){const c=useContext(Context);if(!c)throw Error("StoreProvider missing");return c}
